//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

DATA gclocals·untyped(SB)/8, $1
GLOBL gclocals·untyped(SB), 8, $8

TEXT ·_c2goasm_native_sum_u32(SB), 516, $0-0

    CBZ R1, sum_u32_LBB0_3
    CMP $3, R1 // cmp	x1, #3
    BHI sum_u32_LBB0_4
    MOVD $0, R9 // mov	x9, #0
    MOVD $0, R8 // mov	x8, #0
    B sum_u32_LBB0_13
sum_u32_LBB0_3:
    MOVD $0, R8 // mov	x8, #0
    MOVD R8, R0 // mov	x0, x8
    RET
sum_u32_LBB0_4:
    CMP $16, R1 // cmp	x1, #16
    BHS sum_u32_LBB0_6
    MOVD $0, R9 // mov	x9, #0
    MOVD $0, R8 // mov	x8, #0
    B sum_u32_LBB0_10
sum_u32_LBB0_6:
    WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
    AND $-16, R1, R9 // and	x9, x1, #0xfffffffffffffff0
    WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
    ADD $32, R0, R8 // add	x8, x0, #32
    MOVD R9, R10 // mov	x10, x9
    WORD $0x6f00e403 // movi.2d	v3, #0000000000000000
    WORD $0x6f00e404 // movi.2d	v4, #0000000000000000
    WORD $0x6f00e405 // movi.2d	v5, #0000000000000000
    WORD $0x6f00e402 // movi.2d	v2, #0000000000000000
    WORD $0x6f00e407 // movi.2d	v7, #0000000000000000
    WORD $0x6f00e406 // movi.2d	v6, #0000000000000000
sum_u32_LBB0_7:
    WORD $0xad7f4510 // ldp	q16, q17, [x8, #-32]
    VUADDW2 V16.S4, V1.D2, V1.D2 // uaddw2.2d	v1, v1, v16
    VUADDW V16.S2, V0.D2, V0.D2 // uaddw.2d	v0, v0, v16
    WORD $0xacc24910 // ldp	q16, q18, [x8], #64
    VUADDW2 V17.S4, V4.D2, V4.D2 // uaddw2.2d	v4, v4, v17
    VUADDW V17.S2, V3.D2, V3.D2 // uaddw.2d	v3, v3, v17
    VUADDW2 V16.S4, V2.D2, V2.D2 // uaddw2.2d	v2, v2, v16
    VUADDW V16.S2, V5.D2, V5.D2 // uaddw.2d	v5, v5, v16
    VUADDW2 V18.S4, V6.D2, V6.D2 // uaddw2.2d	v6, v6, v18
    VUADDW V18.S2, V7.D2, V7.D2 // uaddw.2d	v7, v7, v18
    SUBS $16, R10, R10 // subs	x10, x10, #16
    BNE sum_u32_LBB0_7
    VADD V0.D2, V3.D2, V0.D2 // add.2d	v0, v3, v0
    VADD V1.D2, V4.D2, V1.D2 // add.2d	v1, v4, v1
    VADD V5.D2, V7.D2, V3.D2 // add.2d	v3, v7, v5
    VADD V0.D2, V3.D2, V0.D2 // add.2d	v0, v3, v0
    VADD V2.D2, V6.D2, V2.D2 // add.2d	v2, v6, v2
    VADD V1.D2, V2.D2, V1.D2 // add.2d	v1, v2, v1
    VADD V1.D2, V0.D2, V0.D2 // add.2d	v0, v0, v1
    WORD $0x5ef1b800 // addp.2d	d0, v0
    WORD $0x9e660008 // fmov	x8, d0
    CMP R9, R1 // cmp	x1, x9
    BEQ sum_u32_LBB0_15
    TST $12, R1 // tst	x1, #0xc
    BEQ sum_u32_LBB0_13
sum_u32_LBB0_10:
    MOVD R9, R10 // mov	x10, x9
    AND $-4, R1, R9 // and	x9, x1, #0xfffffffffffffffc
    WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
    WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
    VMOV R8, V1.D[0] // mov.d	v1[0], x8
    SUB R9, R10, R8 // sub	x8, x10, x9
    ADD R10<<2, R0, R10 // add	x10, x0, x10, lsl #2
sum_u32_LBB0_11:
    WORD $0x3cc10542 // ldr	q2, [x10], #16
    VUADDW2 V2.S4, V0.D2, V0.D2 // uaddw2.2d	v0, v0, v2
    VUADDW V2.S2, V1.D2, V1.D2 // uaddw.2d	v1, v1, v2
    ADDS $4, R8, R8 // adds	x8, x8, #4
    BNE sum_u32_LBB0_11
    VADD V0.D2, V1.D2, V0.D2 // add.2d	v0, v1, v0
    WORD $0x5ef1b800 // addp.2d	d0, v0
    WORD $0x9e660008 // fmov	x8, d0
    CMP R9, R1 // cmp	x1, x9
    BEQ sum_u32_LBB0_15
sum_u32_LBB0_13:
    SUB R9, R1, R10 // sub	x10, x1, x9
    ADD R9<<2, R0, R9 // add	x9, x0, x9, lsl #2
sum_u32_LBB0_14:
    WORD $0xb840452b // ldr	w11, [x9], #4
    ADD R11, R8, R8 // add	x8, x8, x11
    SUBS $1, R10, R10 // subs	x10, x10, #1
    BNE sum_u32_LBB0_14
sum_u32_LBB0_15:
    MOVD R8, R0 // mov	x0, x8
    RET


TEXT ·_sum_u32(SB), 4, $0-24

    MOVD input+0(FP), R0
    MOVD size+8(FP), R1
    CALL ·_c2goasm_native_sum_u32(SB)
    MOVD R0, ret+16(FP)
    RET


TEXT ·_c2goasm_native_add_u32(SB), 516, $0-0

    CBZ R3, add_u32_LBB1_5
    CMP $3, R3 // cmp	x3, #3
    BHI add_u32_LBB1_6
    MOVD $0, R8 // mov	x8, #0
add_u32_LBB1_3:
    SUB R8, R3, R9 // sub	x9, x3, x8
    LSL $2, R8, R11 // lsl	x11, x8, #2
    ADD R11, R2, R8 // add	x8, x2, x11
    ADD R11, R1, R10 // add	x10, x1, x11
    ADD R11, R0, R11 // add	x11, x0, x11
add_u32_LBB1_4:
    WORD $0xb840456c // ldr	w12, [x11], #4
    WORD $0xb840454d // ldr	w13, [x10], #4
    ADDW R12, R13, R12 // add	w12, w13, w12
    WORD $0xb800450c // str	w12, [x8], #4
    SUBS $1, R9, R9 // subs	x9, x9, #1
    BNE add_u32_LBB1_4
add_u32_LBB1_5:
    RET
add_u32_LBB1_6:
    MOVD $0, R8 // mov	x8, #0
    SUB R0, R2, R9 // sub	x9, x2, x0
    CMP $64, R9 // cmp	x9, #64
    BLO add_u32_LBB1_3
    SUB R1, R2, R9 // sub	x9, x2, x1
    CMP $64, R9 // cmp	x9, #64
    BLO add_u32_LBB1_3
    CMP $16, R3 // cmp	x3, #16
    BHS add_u32_LBB1_10
    MOVD $0, R8 // mov	x8, #0
    B add_u32_LBB1_14
add_u32_LBB1_10:
    AND $-16, R3, R8 // and	x8, x3, #0xfffffffffffffff0
    ADD $32, R0, R9 // add	x9, x0, #32
    ADD $32, R1, R10 // add	x10, x1, #32
    ADD $32, R2, R11 // add	x11, x2, #32
    MOVD R8, R12 // mov	x12, x8
add_u32_LBB1_11:
    WORD $0xad7f0520 // ldp	q0, q1, [x9, #-32]
    WORD $0xacc20d22 // ldp	q2, q3, [x9], #64
    WORD $0xad7f1544 // ldp	q4, q5, [x10, #-32]
    WORD $0xacc21d46 // ldp	q6, q7, [x10], #64
    VADD V0.S4, V4.S4, V0.S4 // add.4s	v0, v4, v0
    VADD V1.S4, V5.S4, V1.S4 // add.4s	v1, v5, v1
    VADD V2.S4, V6.S4, V2.S4 // add.4s	v2, v6, v2
    VADD V3.S4, V7.S4, V3.S4 // add.4s	v3, v7, v3
    WORD $0xad3f0560 // stp	q0, q1, [x11, #-32]
    WORD $0xac820d62 // stp	q2, q3, [x11], #64
    SUBS $16, R12, R12 // subs	x12, x12, #16
    BNE add_u32_LBB1_11
    CMP R8, R3 // cmp	x3, x8
    BEQ add_u32_LBB1_5
    TST $12, R3 // tst	x3, #0xc
    BEQ add_u32_LBB1_3
add_u32_LBB1_14:
    MOVD R8, R10 // mov	x10, x8
    AND $-4, R3, R8 // and	x8, x3, #0xfffffffffffffffc
    SUB R8, R10, R9 // sub	x9, x10, x8
    LSL $2, R10, R12 // lsl	x12, x10, #2
    ADD R12, R2, R10 // add	x10, x2, x12
    ADD R12, R1, R11 // add	x11, x1, x12
    ADD R12, R0, R12 // add	x12, x0, x12
add_u32_LBB1_15:
    WORD $0x3cc10580 // ldr	q0, [x12], #16
    WORD $0x3cc10561 // ldr	q1, [x11], #16
    VADD V0.S4, V1.S4, V0.S4 // add.4s	v0, v1, v0
    WORD $0x3c810540 // str	q0, [x10], #16
    ADDS $4, R9, R9 // adds	x9, x9, #4
    BNE add_u32_LBB1_15
    CMP R8, R3 // cmp	x3, x8
    BNE add_u32_LBB1_3
    B add_u32_LBB1_5


TEXT ·_add_u32(SB), 4, $0-32

    MOVD a+0(FP), R0
    MOVD b+8(FP), R1
    MOVD dst+16(FP), R2
    MOVD size+24(FP), R3
    CALL ·_c2goasm_native_add_u32(SB)
    RET
