//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

DATA gclocals·untyped(SB)/8, $1
GLOBL gclocals·untyped(SB), 8, $8

TEXT ·_c2goasm_native_sum_u32(SB), 516, $0-0

    LONG $0xfa1e0ff3 // endbr64
    WORD $0x8548; BYTE $0xf6 // test	rsi, rsi
    JEQ sum_u32_L9
    LONG $0xff468d48 // lea	rax, -1[rsi]
    LONG $0x06f88348 // cmp	rax, 6
    JLS sum_u32_L10
    WORD $0x8948; BYTE $0xf2 // mov	rdx, rsi
    WORD $0x8948; BYTE $0xf8 // mov	rax, rdi
    LONG $0xd2efe9c5 // vpxor	xmm2, xmm2, xmm2
    LONG $0x03eac148 // shr	rdx, 3
    LONG $0x05e2c148 // sal	rdx, 5
    WORD $0x0148; BYTE $0xfa // add	rdx, rdi
sum_u32_L4:
    LONG $0x006ffec5 // vmovdqu	ymm0, YMMWORD PTR [rax]
    LONG $0x20c08348 // add	rax, 32
    LONG $0x357de2c4; BYTE $0xc8 // vpmovzxdq	ymm1, xmm0
    LONG $0x397de3c4; WORD $0x01c0 // vextracti128	xmm0, ymm0, 0x1
    LONG $0x357de2c4; BYTE $0xc0 // vpmovzxdq	ymm0, xmm0
    LONG $0xc0d4f5c5 // vpaddq	ymm0, ymm1, ymm0
    LONG $0xd0d4edc5 // vpaddq	ymm2, ymm2, ymm0
    WORD $0x3948; BYTE $0xd0 // cmp	rax, rdx
    JNE sum_u32_L4
    LONG $0x397de3c4; WORD $0x01d1 // vextracti128	xmm1, ymm2, 0x1
    LONG $0xcad4f1c5 // vpaddq	xmm1, xmm1, xmm2
    LONG $0xd973f9c5; BYTE $0x08 // vpsrldq	xmm0, xmm1, 8
    LONG $0xc0d4f1c5 // vpaddq	xmm0, xmm1, xmm0
    LONG $0x7ef9e1c4; BYTE $0xc0 // vmovq	rax, xmm0
    LONG $0x07c6f640 // test	sil, 7
    JEQ sum_u32_L18
    WORD $0x8948; BYTE $0xf2 // mov	rdx, rsi
    LONG $0xf8e28348 // and	rdx, -8
    WORD $0xf8c5; BYTE $0x77 // vzeroupper
sum_u32_L3:
    WORD $0x8948; BYTE $0xf1 // mov	rcx, rsi
    WORD $0x2948; BYTE $0xd1 // sub	rcx, rdx
    LONG $0xff418d4c // lea	r8, -1[rcx]
    LONG $0x02f88349 // cmp	r8, 2
    JLS sum_u32_L7
    LONG $0x146ffac5; BYTE $0x97 // vmovdqu	xmm2, XMMWORD PTR [rdi+rdx*4]
    LONG $0x3579e2c4; BYTE $0xc2 // vpmovzxdq	xmm0, xmm2
    LONG $0xda73e9c5; BYTE $0x08 // vpsrldq	xmm2, xmm2, 8
    LONG $0x3579e2c4; BYTE $0xd2 // vpmovzxdq	xmm2, xmm2
    LONG $0xc2d4f9c5 // vpaddq	xmm0, xmm0, xmm2
    LONG $0xc1d4f9c5 // vpaddq	xmm0, xmm0, xmm1
    LONG $0xd873f1c5; BYTE $0x08 // vpsrldq	xmm1, xmm0, 8
    LONG $0xc1d4f9c5 // vpaddq	xmm0, xmm0, xmm1
    LONG $0x7ef9e1c4; BYTE $0xc0 // vmovq	rax, xmm0
    WORD $0xc1f6; BYTE $0x03 // test	cl, 3
    JEQ sum_u32_L1
    LONG $0xfce18348 // and	rcx, -4
    WORD $0x0148; BYTE $0xca // add	rdx, rcx
sum_u32_L7:
    WORD $0x0c8b; BYTE $0x97 // mov	ecx, DWORD PTR [rdi+rdx*4]
    WORD $0x0148; BYTE $0xc8 // add	rax, rcx
    LONG $0x014a8d48 // lea	rcx, 1[rdx]
    WORD $0x3948; BYTE $0xf1 // cmp	rcx, rsi
    JCC sum_u32_L1
    LONG $0x04974c8b // mov	ecx, DWORD PTR 4[rdi+rdx*4]
    WORD $0x0148; BYTE $0xc8 // add	rax, rcx
    LONG $0x024a8d48 // lea	rcx, 2[rdx]
    WORD $0x3948; BYTE $0xf1 // cmp	rcx, rsi
    JCC sum_u32_L1
    LONG $0x0897548b // mov	edx, DWORD PTR 8[rdi+rdx*4]
    WORD $0x0148; BYTE $0xd0 // add	rax, rdx
    RET
sum_u32_L18:
    WORD $0xf8c5; BYTE $0x77 // vzeroupper
sum_u32_L1:
    RET
sum_u32_L9:
    WORD $0xc031 // xor	eax, eax
    RET
sum_u32_L10:
    LONG $0xc9eff1c5 // vpxor	xmm1, xmm1, xmm1
    WORD $0xd231 // xor	edx, edx
    WORD $0xc031 // xor	eax, eax
    JMP sum_u32_L3


TEXT ·_sum_u32(SB), 4, $0-24

    MOVQ input+0(FP), DI
    MOVQ size+8(FP), SI
    CALL ·_c2goasm_native_sum_u32(SB)
    PXOR X15, X15
    MOVQ AX, ret+16(FP)
    RET


TEXT ·_c2goasm_native_add_u32(SB), 516, $0-0

    LONG $0xfa1e0ff3 // endbr64
    WORD $0x8548; BYTE $0xc9 // test	rcx, rcx
    JEQ add_u32_L52
    LONG $0xff418d4c // lea	r8, -1[rcx]
    LONG $0x02f88349 // cmp	r8, 2
    JLS add_u32_L31
    LONG $0xfc428d48 // lea	rax, -4[rdx]
    WORD $0x8949; BYTE $0xc1 // mov	r9, rax
    WORD $0x2949; BYTE $0xf9 // sub	r9, rdi
    LONG $0x18f98349 // cmp	r9, 24
    JLS add_u32_L31
    WORD $0x2948; BYTE $0xf0 // sub	rax, rsi
    LONG $0x18f88348 // cmp	rax, 24
    JLS add_u32_L31
    LONG $0x06f88349 // cmp	r8, 6
    WORD $0x8949; BYTE $0xc8 // mov	r8, rcx
    JLS add_u32_L32
    LONG $0x03e8c149 // shr	r8, 3
    WORD $0xc031 // xor	eax, eax
    LONG $0x05e0c149 // sal	r8, 5
add_u32_L24:
    LONG $0x046ffec5; BYTE $0x06 // vmovdqu	ymm0, YMMWORD PTR [rsi+rax]
    LONG $0x04fefdc5; BYTE $0x07 // vpaddd	ymm0, ymm0, YMMWORD PTR [rdi+rax]
    LONG $0x047ffec5; BYTE $0x02 // vmovdqu	YMMWORD PTR [rdx+rax], ymm0
    LONG $0x20c08348 // add	rax, 32
    WORD $0x394c; BYTE $0xc0 // cmp	rax, r8
    JNE add_u32_L24
    WORD $0xc1f6; BYTE $0x07 // test	cl, 7
    JEQ add_u32_L50
    WORD $0x8949; BYTE $0xc8 // mov	r8, rcx
    WORD $0x8948; BYTE $0xc8 // mov	rax, rcx
    LONG $0x07e08341 // and	r8d, 7
    LONG $0xf8e08348 // and	rax, -8
    LONG $0xff488d4d // lea	r9, -1[r8]
    LONG $0x02f98349 // cmp	r9, 2
    JLS add_u32_L53
    WORD $0xf8c5; BYTE $0x77 // vzeroupper
add_u32_L23:
    LONG $0x046ffac5; BYTE $0x86 // vmovdqu	xmm0, XMMWORD PTR [rsi+rax*4]
    LONG $0x04fef9c5; BYTE $0x87 // vpaddd	xmm0, xmm0, XMMWORD PTR [rdi+rax*4]
    LONG $0x047ffac5; BYTE $0x82 // vmovdqu	XMMWORD PTR [rdx+rax*4], xmm0
    LONG $0x03c0f641 // test	r8b, 3
    JEQ add_u32_L52
    LONG $0xfce08349 // and	r8, -4
    WORD $0x014c; BYTE $0xc0 // add	rax, r8
add_u32_L26:
    LONG $0x86048b44 // mov	r8d, DWORD PTR [rsi+rax*4]
    LONG $0x87040344 // add	r8d, DWORD PTR [rdi+rax*4]
    LONG $0x82048944 // mov	DWORD PTR [rdx+rax*4], r8d
    LONG $0x01408d4c // lea	r8, 1[rax]
    WORD $0x3949; BYTE $0xc8 // cmp	r8, rcx
    JCC add_u32_L52
    LONG $0x86448b44; BYTE $0x04 // mov	r8d, DWORD PTR 4[rsi+rax*4]
    LONG $0x87440344; BYTE $0x04 // add	r8d, DWORD PTR 4[rdi+rax*4]
    LONG $0x82448944; BYTE $0x04 // mov	DWORD PTR 4[rdx+rax*4], r8d
    LONG $0x02408d4c // lea	r8, 2[rax]
    WORD $0x3949; BYTE $0xc8 // cmp	r8, rcx
    JCC add_u32_L52
    LONG $0x08864c8b // mov	ecx, DWORD PTR 8[rsi+rax*4]
    LONG $0x08874c03 // add	ecx, DWORD PTR 8[rdi+rax*4]
    LONG $0x08824c89 // mov	DWORD PTR 8[rdx+rax*4], ecx
    RET
add_u32_L50:
    WORD $0xf8c5; BYTE $0x77 // vzeroupper
add_u32_L52:
    RET
add_u32_L53:
    WORD $0xf8c5; BYTE $0x77 // vzeroupper
    JMP add_u32_L26
add_u32_L31:
    WORD $0xc031 // xor	eax, eax
add_u32_L28:
    LONG $0x86048b44 // mov	r8d, DWORD PTR [rsi+rax*4]
    LONG $0x87040344 // add	r8d, DWORD PTR [rdi+rax*4]
    LONG $0x82048944 // mov	DWORD PTR [rdx+rax*4], r8d
    LONG $0x01c08348 // add	rax, 1
    WORD $0x3948; BYTE $0xc1 // cmp	rcx, rax
    JNE add_u32_L28
    RET
add_u32_L32:
    WORD $0xc031 // xor	eax, eax
    JMP add_u32_L23


TEXT ·_add_u32(SB), 4, $0-32

    MOVQ a+0(FP), DI
    MOVQ b+8(FP), SI
    MOVQ dst+16(FP), DX
    MOVQ size+24(FP), CX
    CALL ·_c2goasm_native_add_u32(SB)
    PXOR X15, X15
    RET
