//go:build amd64 && !nosimd

package simd

import (
	"runtime"
	"unsafe"
)

// Bodyless companion declarations: they explicitly ask c2goasm to emit a Go
// ABI wrapper for the converted C symbols (see simd_amd64.s, generated by
// ./generate.sh).
func _sum_u32(input unsafe.Pointer, size uint64) uint64
func _add_u32(a unsafe.Pointer, b unsafe.Pointer, dst unsafe.Pointer, size uint64)

func SumU32(input []uint32) uint64 {
	if len(input) == 0 {
		return 0
	}
	result := _sum_u32(unsafe.Pointer(&input[0]), uint64(len(input)))
	runtime.KeepAlive(input)
	return result
}

func AddU32(dst, a, b []uint32) {
	_add_u32(unsafe.Pointer(&a[0]), unsafe.Pointer(&b[0]), unsafe.Pointer(&dst[0]), uint64(len(a)))
	runtime.KeepAlive(a)
	runtime.KeepAlive(b)
	runtime.KeepAlive(dst)
}
