// Command c2goasm converts clang-generated assembly (GNU syntax) into
// Go Plan 9 assembly.
package main

import (
	"encoding/hex"
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"

	"github.com/faceair/c2goasm/arch"
	"github.com/faceair/c2goasm/internal/asm"
	"github.com/faceair/c2goasm/internal/asm2plan9s"
)

type Options struct {
	Assemble bool // -a: kept for CLI compatibility; encoding is always on
	Strip    bool // -s: strip generated comments
	Compact  bool // -c: compact byte code lines
	Format   bool // -f: format with asmfmt
	Target   string
}

func main() {
	opts, args, err := parseArgs(os.Args[1:])
	if err != nil {
		log.Fatal(err)
	}
	if err := Run(opts, args); err != nil {
		log.Fatal(err)
	}
}

func parseArgs(args []string) (Options, []string, error) {
	fs := flag.NewFlagSet("c2goasm", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)

	assembleFlag := fs.Bool("a", false, "Immediately invoke asm2plan9s")
	stripFlag := fs.Bool("s", false, "Strip comments")
	compactFlag := fs.Bool("c", false, "Compact byte codes")
	formatFlag := fs.Bool("f", false, "Format using asmfmt")
	targetFlag := fs.String("t", "amd64", "Target architecture of input code (amd64 or arm64)")

	if err := fs.Parse(args); err != nil {
		return Options{}, nil, fmt.Errorf("parseArgs: %w", err)
	}
	return Options{
		Assemble: *assembleFlag,
		Strip:    *stripFlag,
		Compact:  *compactFlag,
		Format:   *formatFlag,
		Target:   *targetFlag,
	}, fs.Args(), nil
}

// Run executes the converter with explicit args (source, dest).
func Run(opts Options, args []string) (err error) {
	defer func() {
		if r := recover(); err == nil && r != nil {
			err = fmt.Errorf("unexpected panic: %v", r)
		}
	}()

	desc, err := arch.Resolve(opts.Target)
	if err != nil {
		return fmt.Errorf("target: %w", err)
	}

	if len(args) < 2 {
		return fmt.Errorf("run: validate args: not enough input files specified\n\nusage: c2goasm [-t amd64|arm64] /path/to/project/file.s output.s")
	}
	srcFile := args[0]
	assemblyFile := args[1]
	if !hasSuffix(assemblyFile, ".s") {
		return fmt.Errorf("run: validate args: destination file %q must have '.s' extension", assemblyFile)
	}

	goCompanion := assemblyFile[:len(assemblyFile)-2] + ".go"
	companionSrc, err := os.ReadFile(goCompanion)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("run: validate args: companion '.go' file %q is missing for destination %q", goCompanion, assemblyFile)
		}
		return fmt.Errorf("run: validate args: read companion '.go' file %q: %w", goCompanion, err)
	}

	fmt.Println("Processing", srcFile)
	lines, err := readLines(srcFile)
	if err != nil {
		return fmt.Errorf("readLines: %w", err)
	}

	enc := asm2plan9s.NewEncoder(desc)
	result, err := asm.Process(lines, companionSrc, desc, enc)
	if err != nil {
		return err
	}

	if err := writeLines(result, assemblyFile, true); err != nil {
		return fmt.Errorf("writeLines: %w", err)
	}

	if opts.Strip {
		if err := stripGoasmComments(assemblyFile); err != nil {
			return err
		}
	}
	if opts.Compact {
		if err := compactOpcodes(assemblyFile); err != nil {
			return err
		}
	}
	if opts.Format {
		if err := formatAssembly(assemblyFile); err != nil {
			return err
		}
	}
	return nil
}

func hasSuffix(s, suffix string) bool {
	return len(s) >= len(suffix) && s[len(s)-len(suffix):] == suffix
}

func readLines(path string) ([]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var lines []string
	start := 0
	for i := 0; i < len(data); i++ {
		if data[i] == '\n' {
			line := data[start:i]
			if len(line) > 0 && line[len(line)-1] == '\r' {
				line = line[:len(line)-1]
			}
			lines = append(lines, string(line))
			start = i + 1
		}
	}
	if start < len(data) {
		lines = append(lines, string(data[start:]))
	}
	return lines, nil
}

func writeLines(lines []string, path string, header bool) error {
	var content []byte
	if header {
		content = append(content, "//+build !noasm !appengine\n"...)
		content = append(content, "// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT\n\n"...)
	}
	for _, line := range lines {
		content = append(content, line...)
		content = append(content, '\n')
	}
	return os.WriteFile(path, content, 0o644)
}

func stripGoasmComments(file string) error {
	lines, err := readLines(file)
	if err != nil {
		return fmt.Errorf("readLines: %w", err)
	}
	for i, l := range lines {
		if containsAny(l, "LONG", "WORD", "BYTE") {
			opcode := ""
			for j := 0; j < len(l); j++ {
				if l[j] == '/' && j+1 < len(l) && l[j+1] == '/' {
					opcode = trimSpace(l[:j])
					break
				}
			}
			if opcode != "" {
				lines[i] = opcode
			}
		}
	}
	return writeLines(lines, file, false)
}

func compactOpcodes(file string) error {
	lines, err := readLines(file)
	if err != nil {
		return fmt.Errorf("compact opcodes: read %q: %w", file, err)
	}

	result := make([]string, 0, len(lines))
	var pending []byte
	flush := func() {
		result = append(result, compactByteArray(pending)...)
		pending = pending[:0]
	}

	for lineNumber, line := range lines {
		code := strings.TrimSpace(strings.SplitN(line, "//", 2)[0])
		bytes, opcodeLine, err := parseOpcodeBytes(code)
		if err != nil {
			return fmt.Errorf("compact opcodes: line %d %q: %w", lineNumber+1, line, err)
		}
		if opcodeLine {
			pending = append(pending, bytes...)
			continue
		}
		if len(pending) > 0 {
			flush()
		}
		result = append(result, line)
	}
	if len(pending) > 0 {
		flush()
	}
	if err := writeLines(result, file, false); err != nil {
		return fmt.Errorf("compact opcodes: write %q: %w", file, err)
	}
	return nil
}

func parseOpcodeBytes(code string) ([]byte, bool, error) {
	if code == "" {
		return nil, false, nil
	}
	widths := map[string]int{"BYTE": 1, "WORD": 2, "LONG": 4, "QUAD": 8}
	var result []byte
	for _, part := range strings.Split(code, ";") {
		fields := strings.Fields(strings.TrimSpace(part))
		if len(fields) == 0 {
			continue
		}
		width, ok := widths[fields[0]]
		if !ok {
			return nil, false, nil
		}
		if len(fields) != 2 || !strings.HasPrefix(fields[1], "$0x") {
			return nil, true, fmt.Errorf("invalid %s literal", fields[0])
		}
		literal := fields[1][3:]
		if len(literal) > width*2 {
			return nil, true, fmt.Errorf("%s literal %q exceeds %d bytes", fields[0], fields[1], width)
		}
		literal = strings.Repeat("0", width*2-len(literal)) + literal
		encoded, err := hex.DecodeString(literal)
		if err != nil {
			return nil, true, fmt.Errorf("decode %s literal %q: %w", fields[0], fields[1], err)
		}
		for i := len(encoded) - 1; i >= 0; i-- {
			result = append(result, encoded[i])
		}
	}
	return result, true, nil
}

func compactByteArray(opcodes []byte) []string {
	var result []string
	for len(opcodes) >= 16 {
		result = append(result, fmt.Sprintf("    QUAD $0x%s; QUAD $0x%s",
			reverseHex(opcodes[:8]), reverseHex(opcodes[8:16])))
		opcodes = opcodes[16:]
	}
	if len(opcodes) >= 8 {
		result = append(result, fmt.Sprintf("    QUAD $0x%s", reverseHex(opcodes[:8])))
		opcodes = opcodes[8:]
	}
	if len(opcodes) > 0 {
		var parts []string
		if len(opcodes) >= 4 {
			parts = append(parts, "LONG $0x"+reverseHex(opcodes[:4]))
			opcodes = opcodes[4:]
		}
		if len(opcodes) >= 2 {
			parts = append(parts, "WORD $0x"+reverseHex(opcodes[:2]))
			opcodes = opcodes[2:]
		}
		if len(opcodes) == 1 {
			parts = append(parts, "BYTE $0x"+reverseHex(opcodes))
		}
		result = append(result, "    "+strings.Join(parts, "; "))
	}
	return result
}

func reverseHex(data []byte) string {
	encoded := make([]byte, hex.EncodedLen(len(data)))
	hex.Encode(encoded, data)
	for left, right := 0, len(encoded)-2; left < right; left, right = left+2, right-2 {
		encoded[left], encoded[right] = encoded[right], encoded[left]
		encoded[left+1], encoded[right+1] = encoded[right+1], encoded[left+1]
	}
	return string(encoded)
}

func formatAssembly(file string) error {
	asmfmt, err := exec.LookPath("asmfmt")
	if err != nil {
		return fmt.Errorf("find asmfmt: %w", err)
	}
	output, err := exec.Command(asmfmt, "-w", file).CombinedOutput()
	if err != nil {
		detail := strings.TrimSpace(string(output))
		if detail != "" {
			return fmt.Errorf("asmfmt %q: %w: %s", file, err, detail)
		}
		return fmt.Errorf("asmfmt %q: %w", file, err)
	}
	return nil
}

func containsAny(s string, subs ...string) bool {
	for _, sub := range subs {
		if contains(s, sub) {
			return true
		}
	}
	return false
}

func contains(s, sub string) bool {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return true
		}
	}
	return false
}

func trimSpace(s string) string {
	start, end := 0, len(s)
	for start < end && (s[start] == ' ' || s[start] == '\t') {
		start++
	}
	for end > start && (s[end-1] == ' ' || s[end-1] == '\t') {
		end--
	}
	return s[start:end]
}
